"use client"
import './globals.css'
import '@rainbow-me/rainbowkit/styles.css';

import {getDefaultWallets, RainbowKitProvider,} from '@rainbow-me/rainbowkit';
import {configureChains, createConfig, WagmiConfig} from 'wagmi';
import {hardhat} from 'wagmi/chains';
import {publicProvider} from 'wagmi/providers/public';

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

const { chains, publicClient } = configureChains(
    [hardhat],
    [
      publicProvider()
    ]
);

const { connectors } = getDefaultWallets({
    appName: 'Voting Project 3',
    projectId: '502b4b7bc660a7df4ffcb6dea5903f7a',
    chains
});

const wagmiConfig = createConfig({
    autoConnect: true,
    connectors,
    publicClient
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
            <WagmiConfig config={wagmiConfig}>
                <RainbowKitProvider chains={chains}>
                    {children}
                </RainbowKitProvider>
            </WagmiConfig>
        </body>
    </html>
  )
}
